// Generated by CoffeeScript 2.5.1
(function() {
  // -*- coffee-tab-width: 4 -*-
  (function($) {
    var cmpFunction, compareNames, compareStrings, games, predFunction, setDefaults, showAll, showGenre, showOccasion, showTable, sortByDate, sortByName;
    games = null;
    predFunction = null;
    cmpFunction = null;
    $(function() {
      return $.ajax({
        url: "games.json",
        dataType: "json",
        success: function(data, _0, _1) {
          games = data;
          return setDefaults();
        }
      });
    });
    compareStrings = function(x, y) {
      switch (false) {
        case !(x > y):
          return 1;
        case !(x < y):
          return -1;
        default:
          return 0;
      }
    };
    compareNames = function(x, y) {
      return compareStrings(x.name, y.name);
    };
    showTable = function() {
      var arr, cmp, finish, game, i, len, parity, pred, str;
      pred = predFunction;
      cmp = cmpFunction;
      arr = games.games.slice(0).filter(pred);
      arr.sort(cmp);
      str = `<tr class='rowhead'>
    <th>Name</th>
    <th>Author(s)</th>
    <th>Genre</th>
    <th>Summary</th>
    <th>Finish Date</th>
    <th>Link</th>
</tr>`;
      parity = 'even';
      for (i = 0, len = arr.length; i < len; i++) {
        game = arr[i];
        finish = `${game.finished[0]}/${game.finished[1]}`;
        parity = (function() {
          switch (parity) {
            case 'even':
              return 'odd';
            case 'odd':
              return 'even';
            default:
              return 'odd';
          }
        })();
        str += `<tr class='row${parity}'>
    <td class='column cname'>${game.name}</td>
    <td class='column cauthor'>${game.author}</td>
    <td class='column cgenre'>${game.genre}</td>
    <td class='column csummary'>${game.summary}</td>
    <td class='column cfinish'>${finish}</td>
    <td class='column cpage'>
        <a href='${game.page}' target='new'>Link</a>
    </td>
</tr>`;
      }
      return $("table#games-table").html(str);
    };
    setDefaults = function() {
      cmpFunction = compareNames;
      return showAll();
    };
    showAll = function() {
      predFunction = function(_0) {
        return true;
      };
      return showTable();
    };
    showGenre = function(regexp) {
      predFunction = function(obj) {
        return obj.genre.match(regexp);
      };
      return showTable();
    };
    showOccasion = function(occasion) {
      predFunction = function(obj) {
        return obj.occasion === occasion;
      };
      return showTable();
    };
    sortByName = function() {
      cmpFunction = compareNames;
      return showTable();
    };
    sortByDate = function() {
      cmpFunction = function(x, y) {
        var x0, y0;
        [x0, y0] = [x.finished, y.finished];
        switch (false) {
          case !(x0[1] > y0[1]):
            return -1;
          case !(x0[1] < y0[1]):
            return 1;
          case !(x0[0] > y0[0]):
            return -1;
          case !(x0[0] < y0[0]):
            return 1;
          default:
            return 0;
        }
      };
      return showTable();
    };
    window.showAll = showAll;
    window.showGenre = showGenre;
    window.showOccasion = showOccasion;
    window.sortByName = sortByName;
    return window.sortByDate = sortByDate;
  })(jQuery);

}).call(this);
